[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "Ab2ScbQzLejfeGDkTeqcGd5LG2jfqbMqnE8Jdyni3Bot"

[programs.devnet]
contract = "Ab2ScbQzLejfeGDkTeqcGd5LG2jfqbMqnE8Jdyni3Bot"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/degencodebeast/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
